baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[params]
  disableExplicitIndexURLs = true
[outputs]
home = [ "HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]
  theme = 'hugo-theme-relearn'

